FROM clamsproject/clams-python:0.4.4

RUN apt-get update && apt-get -y install vim curl

WORKDIR ./app

RUN pip install lapps==0.0.2
RUN pip install spacy==3.0.3
RUN pip install spacy-dbpedia-spotlight==0.2.0
RUN python -m spacy download en_core_web_sm

COPY ./ ./

CMD ["python", "app.py", "--develop"]
